# Generated by Django 5.1.1 on 2024-09-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0002_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='finding_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safety_report.findingclassification'),
        ),
    ]
