# Generated by Django 5.1.1 on 2024-09-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0003_findingclassification_finding_finding_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finding',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='safety_report.project'),
        ),
    ]
