# Generated by Django 5.1.1 on 2024-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0004_finding_description_alter_finding_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='findings/'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='before_image',
            field=models.ImageField(upload_to='findings/'),
        ),
    ]
