# Generated by Django 5.1.1 on 2024-09-30 02:42

import safety_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0005_alter_finding_after_image_alter_finding_before_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingclassification',
            name='weighting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finding',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to=safety_report.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='finding',
            name='before_image',
            field=models.ImageField(upload_to=safety_report.models.get_image_path),
        ),
    ]
