# Generated by Django 5.1.1 on 2024-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0006_findingclassification_weighting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
