# Generated by Django 5.1.1 on 2024-09-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0007_alter_finding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='finding_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety_report.findingclassification'),
        ),
    ]
