# Generated by Django 5.1.1 on 2024-10-10 22:27

import safety_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0009_finding_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_image',
            field=models.ImageField(blank=True, null=True, upload_to=safety_report.models.get_pdf_image_path),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_plan',
            field=models.FileField(null=True, upload_to='projects/plans/'),
        ),
    ]
