# Generated by Django 5.1.1 on 2024-10-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_report', '0011_finding_pin_x_finding_pin_y_alter_project_pdf_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='finding',
            new_name='finding_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='before_comment',
        ),
    ]
